# @package _global_
pickle_normal: /host/volatile/jc225751/Runs/29_MIDL_2022_clean/Input/Processed_External/crops/CINGULATE/mask/sulcus_based/2mm/centered_combined/hcp/Rskeleton.pkl
pickle_benchmark: 
train_val_csv_file: /host/volatile/jc225751/Runs/29_MIDL_2022_clean/Input/HCP_half_1bis.csv
nb_subjects: -1
