# @package _global_
pickle_normal: /neurospin/dico/data/deep_folding/current/crops/CINGULATE/mask/sulcus_based/1mm/centered_combined/hcp/Rskeleton.pkl
pickle_benchmark: 
train_val_csv_file: /neurospin/dico/data/deep_folding/current/train_HCP_951.csv
nb_subjects: -1
