# @package _global_
pickle_normal: ../../../Input/crops/CINGULATE/mask/sulcus_based/2mm/centered_combined/hcp/Rskeleton.pkl
pickle_benchmark: 
train_val_csv_file: ../../../Input/HCP_half_1bis.csv
nb_subjects: -1
